plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.6'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'urbantitan'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

tasks.register('runApplication') {
    group = 'application'
    description = 'Runs bootRun while skipping tests (equivalent to `./gradlew bootRun`)'
    doFirst {
        tasks.withType(Test).configureEach { enabled = false }
    }
    dependsOn 'bootRun'
}

tasks.register('localRun') {
    group = 'application'
    description = 'Runs bootRun with remote configs (equivalent to `./gradlew test bootRun`)'
    doFirst{
        tasks.withType(Test).configureEach { enabled = false }
    }
}


repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	implementation 'org.modelmapper:modelmapper:3.2.0'
	implementation 'org.flywaydb:flyway-core:11.11.2'
	implementation 'org.flywaydb:flyway-database-postgresql:11.11.2'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
    implementation 'com.google.http-client:google-http-client-gson:1.43.3'
    runtimeOnly 'org.postgresql:postgresql:42.7.3'
	annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'
    implementation 'com.google.api-client:google-api-client:2.4.0'
}

tasks.named('test') {
	useJUnitPlatform()
}

test {
    // Disable running tests during build
    enabled = false
}
