# spring.application.name=code
# spring.security.oauth2.client.registration.google.client-id=${AUTH_GOOGLE_ID}
# spring.security.oauth2.client.registration.google.client-secret=${AUTH_GOOGLE_SECRET}
# spring.security.oauth2.client.registration.google.scope=email,profile
# spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.username=postgres.aglsjzngppkeliauzfiy
spring.datasource.password=Mhrithik450@
spring.datasource.driverClassName = org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres