import localFont from "next/font/local";
import { Header } from "@/components/navbar";
import { Footer } from "@/components/footer";
import type { Metadata } from "next";
import "./globals.css";

const sfPro = localFont({
  src: [
    {
      path: "../assets/fonts/SF-Pro-Display-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/SF-Pro-Display-Medium.otf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../assets/fonts/SF-Pro-Display-Bold.otf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-sfpro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={sfPro.variable}>
      <body className="antialiased">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
