spring:
  application:
    name: UrbanTitan
  datasource:
    url: jdbc:postgresql://localhost:5432/UrbanTitan
    username: khadiuzz
    password: Tawakkul
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
google:
  oauth:
    client-id: 832116839355-48a8rih6jiq88so34mdd9s4apdfsqlkb.apps.googleusercontent.com