spring.devtools.add-properties=true

logging.level.web=DEBUG

# Disable Flyway if no migrations exist
spring.flyway.enabled=false

spring.jpa.show-sql=false

spring.application.name=UrbanTitan
spring.profiles.active=${SPRING_PROFILE:remote}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}