spring:
  datasource:
    url: jdbc:postgresql://db.kkhjaydeatcawfjtjvjk.supabase.co:5432/postgres
    username: postgres
    password: Gussail2annoyed@53
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
google:
  oauth:
    client-id: 832116839355-48a8rih6jiq88so34mdd9s4apdfsqlkb.apps.googleusercontent.com